CREATE TABLE IF NOT EXISTS contact (
    id BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    prenume VARCHAR(255) NOT NULL,
    nume VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    mesaj TEXT NOT NULL,
    read_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)